let request = require('request-promise');
const fs = require('fs');
const path = require('path');
const isLoggedIn = require('../util/isLoggedIn');
const getCSRF = require('../util/getCSRF');
const { green, red } = require('chalk');
const watch = require('../util/watch');
const FileCookieStore = require('tough-cookie-file-store').FileCookieStore;

const { cookiepath } = require('../constants/index');

if (!fs.existsSync(cookiepath)) {
	fs.writeFileSync(cookiepath, '{}');
}

const cookieJar = request.jar(new FileCookieStore(cookiepath));

request = request.defaults({ jar: cookieJar });

const findErrorBody = body => {
	return body.match(/error[a-zA-Z_\\-\\ ]*">(.*?)<\/span>/g);
};

module.exports = async problem => {
	try {
		if (!isLoggedIn()) {
			return;
		}
		if (!fs.existsSync('.info')) {
			throw Error('Please run inside a folder generated by cf contest');
		}
		problem = problem.toUpperCase();
		const info = JSON.parse(fs.readFileSync('.info'));
		const extension = info.template.extension;
		if (!fs.existsSync(`${problem}.${extension}`)) {
			throw Error('Problem not present in this contest.');
		}
		const filePath = path.join(`${problem}.${extension}`);

		const body = await request.get(
			`https://codeforces.com/contest/${info.contest_number}/submit`
		);

		const token = getCSRF(body);

		const submitUrl = `https://codeforces.com/contest/${info.contest_number}/submit?csrf_token=${token}`;

		const source = fs.readFileSync(filePath).toString();

		request
			.post(submitUrl, {
				form: {
					csrf_token: token,
					action: 'submitSolutionFormSubmitted',
					submittedProblemIndex: problem,
					programTypeId: info.template.lang,
					source,
					tabSize: 4,
					_tta: '790'
				}
			})
			.then(body => {
				console.log(red('Submission Failed ❌'));
				const errors = findErrorBody(body);
				if (errors.length !== 0) {
					console.log(red(errors[0].split('>')[1].split('<')[0]));
				}
			})
			.catch(e => {
				if (e.statusCode != 302) throw Error();
				console.log(green('Submitted Successfully ✔️'));
				const statusURL = `https://codeforces.com/contest/${info.contest_number}/my`;

				watch(statusURL)
					.then()
					.catch(e => {
						throw Error(e);
					});
			});
	} catch (e) {
		console.log(`${e}`);
	}
};
